# Generated by Django 5.0 on 2026-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_company_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies the user belongs to', related_name='users', to='auths.company', verbose_name='Companies'),
        ),
    ]
