# Generated by Django 5.0 on 2026-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_prevent_subscription_overlapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('kz', 'kz')], default='en', help_text="User's preferred language", max_length=10, verbose_name='Preferred language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text="User's full name", max_length=150, verbose_name='Full name'),
        ),
    ]
